apiVersion: v1
data:
    token: ENC[AES256_GCM,data:4b1PzoUMxwFJGizec0Xvq1vc8Qz/NBc9mr9U4EDXlqpDqvUmkHjPBUyQpVCZpEKE4wTSGNvJT1iGiVnqXCyxT/TzS8OZE1RqUljhGbDqE7v0NjbS8GHNm7cWmHeB3oxXqxDcAVXuyCvGqvReHDOpKcUaEUKgS1iqrKVbjg==,iv:YNGloS23JH6B3SeEPfTNIaph8sB9QaUxMzE5EK9+9qA=,tag:VRpG5vrUyT+EQyz8XkWLgA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/atomic-gke-clusters/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-10-05T10:05:12Z"
          enc: CiQAeELGV3txLBcIiPu+r7yDSzKFkUHnNtdZE0AvjmxCdWCuASYSSQBFjqVmHXvlwnE1rcmjLoBI3acxFssY0hlB/blS1qBw/33w03tj/fnvpfb2qTgYGvhbzeiYFYudW8ZVqbVD14kQlpJorO5x+o8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-05T10:05:13Z"
    mac: ENC[AES256_GCM,data:yuIJv424jmRSJ7sT9lUnGZduPblxjBFOxJ+iOXpOPbdomgsEGiY8VXn2jmFGQmYqIVE/c77TKmGMJVDi0E5ybnw3RhIN/aJ5QwZmClzb49d3JRAORo48VDRYOgk5Jmvf0M5+sntZcv3Fq4GOoDx7ar6JliMOBg7C52NQrvwHKOQ=,iv:fUmEvpUDzeTEPlpzLB/gyG9vmHOC/7g8AWAEggaaWPA=,tag:xFg8+2koMtDjn3DeOhGCrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
